DELETE FROM USERS;
DELETE FROM AUTHORITIES;
INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRSTNAME, ENABLED) VALUES (1,'admin@abc.com','$2a$12$2LgDzakdF3JmnrKA/XJwsOG.shA5aTO6MVHC649oRmowquFp.P8my', 'ADMIN', true);
INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRSTNAME, ENABLED) VALUES (2,'manoj@abc.com','$2a$12$mzGXbDLhJT.qY5KK6Rberu/ojz8g0wXFZFb15iFSCYEZclPiDYmBG', 'MANOJ', true);

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('manoj@abc.com', 'USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('admin@abc.com', 'USER,ADMIN');
